# Generated by Django 4.2 on 2023-05-03 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajxapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ajx',
            new_name='Login',
        ),
    ]
