# Generated by Django 4.2 on 2023-05-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajxapp', '0003_alter_login_password_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
